# =============================================================================
# DigitalOcean App Platform — Backend Only
# =============================================================================
# Usage:
#   1. Create a new app in DO Console → Apps → Create App
#   2. Connect your GitHub repo (apioneorigin/BackendRust, branch: main)
#   3. Paste this spec in Settings → App Spec → Edit
#   4. Replace <your-pg-cluster> / <your-valkey-cluster> below with the
#      names of your managed database clusters (Databases → cluster name)
#   5. Set the remaining SECRET env vars in Settings → Environment Variables
#
# DATABASE_URL and REDIS_URL are auto-injected from the attached database
# components — no manual copy/paste of connection strings needed.
# =============================================================================

name: reality-transformer
region: nyc

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DEPLOYMENT_LIVE

ingress:
  rules:
    - component:
        name: backend
      match:
        path:
          prefix: /

# =============================================================================
# Databases — attach your existing managed clusters here
# =============================================================================
# Replace the cluster_name values with YOUR cluster names from DO Console.
# Once attached, ${db.DATABASE_URL} and ${valkey.DATABASE_URL} are auto-
# injected into the backend service below.
# =============================================================================
databases:
  - name: db
    engine: PG
    production: true
    cluster_name: <your-pg-cluster>

  - name: valkey
    engine: REDIS
    production: true
    cluster_name: <your-valkey-cluster>

services:
  - name: backend
    dockerfile_path: Dockerfile
    source_dir: /
    http_port: 8000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb

    github:
      repo: apioneorigin/BackendRust
      branch: main
      deploy_on_push: true

    health_check:
      http_path: /healthz/
      initial_delay_seconds: 15
      period_seconds: 30
      timeout_seconds: 5
      failure_threshold: 3

    envs:
      # ── Secrets (set values in DO Console UI) ──────────────────────────
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET

      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET

      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET

      # ── Auto-injected from attached database components ────────────────
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}

      - key: REDIS_URL
        scope: RUN_TIME
        value: ${valkey.DATABASE_URL}

      # ── Public config ──────────────────────────────────────────────────
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: production

      - key: HOST
        scope: RUN_TIME
        value: "0.0.0.0"

      - key: PORT
        scope: RUN_TIME
        value: "8000"

      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: ${APP_URL}
